source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'RCMarkdownParser_ExampleAbstract' do
  platform :ios, '9.0'
    
  target 'RCMarkdownParser_Example' do
    pod 'RCMarkdownParser', :path => '../'
    pod 'RichTextVC-iOS'
  end

  target 'RCMarkdownParser_Tests' do
    pod 'RCMarkdownParser', :path => '../'
  end
end
